# Generated by Django 5.2.7 on 2025-10-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='amount_per_day',
            new_name='price_per_day',
        ),
    ]
