# Generated by Django 5.2.7 on 2025-10-06 13:01

import librarian.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='start_date',
            field=models.DateField(default=librarian.services.today),
        ),
    ]
